import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import { cn } from "@/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex h-screen flex-col bg-neutral-900 text-slate-300",
          inter.className
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
